### ISSUE TITLE
Sample weight support for regression problems

### ISSUE THREAD

**Issue by kmedved** [AutoViML/featurewiz#1]
Hello - I just saw this library written up on Medium and it looks very interesting. I wanted to ask about the possibility of adding Sample Weight support for it? Xgboost already has support for it via the [weight](https://xgboost.readthedocs.io/en/latest/python/python_api.html#module-xgboost.sklearn) parameter in the .fit() call, so I'm not sure what would be needed other than updating the API to allow a user to pass sample weights.

Thanks!

**Comment by rsesha** [comment]
Hello kmedved:
It should be possible to send the sample_weight parameter. Let me look into it and update this library if possible.
Ram

**Comment by kmedved** [comment]
Great to hear. Thanks!

**Comment by AutoViML** [comment]
Hi @kmedved 👍 
Sorry it took so long to add sample weight functionality to Auto_TS. It now add sample weights automatically for classification problems. You can see the code here:
```
        if modeltype == 'Multi_Classification':
            wt_array = get_sample_weight_array(y_train)
            dtrain = xgb.DMatrix(x_train, label=y_train, weight=wt_array)
```

It adds sample weights for multi-class problems and adds `scale_pos_weight` for binary class problems as you can see here:

```
scale_pos_weight = get_scale_pos_weight(y_train)
```

I hope this is good for you. if you want to send in a sample weight separately I need to change the input arguments, hence I thought I will do it automatically. Take a look at the latest version:

```
pip install auto_ts --upgrade
```

Thanks
Auto_ViML
