### ISSUE TITLE
dont show chart for more than 1000 features

### ISSUE THREAD

**Issue by reza1615** [AutoViML/featurewiz#109]
for more than 1000 features If the verbos=2 it shows a chart with low readability.
for example the chart in the below link doesnt make sence. Aslo I need the rest of information are needed so set verbos=2
https://github.com/AutoViML/featurewiz/blob/main/examples/Featurewiz_on_2000_variables.ipynb

**Comment by AutoViML** [comment]
Ok fixing it right now to not display the network diagram in SULOV if number of features > 1000.
