### ISSUE TITLE
Universal API required for smooth working 

### ISSUE THREAD

**Issue by GDGauravDutta** [AutoViML/featurewiz#111]
There is multiple ways to work with featureviz , request to keep a universal way to work with the library

**Comment by AutoViML** [comment]
Hi @GDGauravDutta :
Thanks for testing out featurewiz 👍 
I have only two API's for featurewiz: Both of them now work the same using the same underlying algorithms.

The reason the two API's exist is that the old API is still in use among many researchers. The new API is in use among new researchers and students. So I didn't want to disadvantage one group vs. another. 

But their inner workings are the same. Is there a reason you are not happy with one vs. another? Can you please expliain more here?
Thanks
Auto Vimal

**Comment by GDGauravDutta** [comment]
Issue like in available documentation. I have used kaggle as a platform for the last 3 months, I am getting lots of errors with solov. I understand the importance of both. I would like to have both formats used so as we can say it works the same and can help the community with our feedback.

**Comment by GDGauravDutta** [comment]
As an end user, I love to experiment with new ideas & Library. I found your repo with my quick experiment.

**Comment by AutoViML** [comment]
Hi @GDGauravDutta 
You mentioned " I am getting lots of errors with solov."

Can you point me links to your Kagge notebooks where you are getting errors with Sulov? I'd like to take a look and troubleshoot if I can.
Thanks
Auto Vimal
