### ISSUE TITLE
Unpin requirements?

### ISSUE THREAD

**Issue by ecederstrand** [AutoViML/featurewiz#112]
featurewiz currently has restrictions on e.g. pandas<2.0, scipy<1.11.0 and xgboost<=1.6.2. These packages are getting a bit outdated. Is there anything holding back versions for these packages?

**Comment by AutoViML** [comment]
Hi Erik: @ecederstrand 
👍 thank you for trying out featurewiz.

pandas 2.0 is a horrible release. They broke 1000's of libraries that have been working forever. Do you really want to upgrade to pandas 2.0 just for the sake of keeping up with your neighbors? I can fix featurewiz to handle pandas 2.0 but once your machine is upgraded to pandas-2.0, 1000's of other libraries will stop working. Are you ready to take that risk??

Scipy 1.11.1 was released in June 28, 2023 - that's less than a year old. How is that outdated??

Can you please answer the questions above and I will then act upon your recommendation...
Thanks
Ram

**Comment by brandonros** [comment]
This is preventing me from using this otherwise very cool looking library. All sorts of build errors.

**Comment by bwhartlove** [comment]
I'll second these notions. Trying to install on Python3.12 and held up because of the scikit-learn pin that does not support Python3.12.

**Comment by rajshah4** [comment]
I wanted to include this in a feature selection tutorial, but I'm having trouble running it. This library uses Dask, which requires panda>2.0.

**Comment by AakashKeswani** [comment]
@AutoViML any decision on the pandas requirement upgrade? It is blocking me from using it with other libraries that require newer versions

**Comment by arturdaraujo** [comment]
An update on featurewiz requirements would be great! Also for xgboost

**Comment by ecederstrand** [comment]
I'm no longer using this package. Closing.

**Comment by arturdaraujo** [comment]
@ecederstrand are you using another? Could you comment here which one?

**Comment by ecederstrand** [comment]
Nope, I'm not using an alternative package.
