### ISSUE TITLE
Conda package outdated

### ISSUE THREAD

**Issue by jmakov** [AutoViML/featurewiz#113]
Latest version on PyPI is 0.5.7, latest conda package version 0.3.2

**Comment by arturdaraujo** [comment]
I'm the maintainer of the conda-forge version, I updated it today

**Comment by lvfmc85** [comment]
I just installed featurewiz with "conda install -c conda-forge featurewiz" and the version installed is still outdated (0.3.2). Am I doing something wrong?

**Comment by arturdaraujo** [comment]
No, I had some problems updating that package on Conda Forge. I am still waiting on the conda-forge community but feel free to try to solve this issue:

https://conda-forge.org/docs/

I will have a look at it eventually but feel free to try

**Comment by mfansler** [comment]
Should be fixed with https://github.com/conda-forge/featurewiz-feedstock/pull/40.

**Comment by arturdaraujo** [comment]
This package is now officially updated thanks to @mfansler
