### ISSUE TITLE
dask_xgboost_error: 'Series' object has no attribute 'compute‘

### ISSUE THREAD

**Issue by zw10** [AutoViML/featurewiz#12]
Encountering the below error (environment WSL:Ubuntu) when trying to run with `dask_xgboost_flag` enabled

```
~/.local/lib/python3.8/site-packages/featurewiz/featurewiz.py in featurewiz(dataname, target, corr_limit, verbose, sep, header, test_data, feature_engg, category_encoders, dask_xgboost_flag, nrows, **kwargs)
   1340             if dask_xgboost_flag:
   1341                 ### since y_train is dask df and data_tuple.X_train is a pandas df, you can't merge them.
-> 1342                 y_test = y_test.compute()  ### remember you first have to convert them to a pandas df
   1343             data2 = data_tuple.X_test.join(y_test)
   1344             dataname = data1.append(data2)

~/.local/lib/python3.8/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5485         ):
   5486             return self[name]
-> 5487         return object.__getattribute__(self, name)
   5488 
   5489     def __setattr__(self, name: str, value) -> None:

AttributeError: 'Series' object has no attribute 'compute'
```

**Comment by AutoViML** [comment]
Hi @zw10 👍 
I assume you are using the latest version. Can you confirm?

There is a dask data related problem when I see an issue like this. Can you please help me? 
2. From the error, it seems that the dataset `y_test (test data)` is being assumed to be `dask` by featurewiz while it is not. Can you please post your `calling statement` for `featurewiz`? That and a few lines of `data (both train and test)` would help.

you can attach the data snippet as a zip file and drop it in the comment section. It accepts zip files only as attachments.

Thank you,
AutoViML

**Comment by zw10** [comment]
Hi - thanks for the quick response! 

Yes using the latest version as far I'm aware - 0.80. Agreed - for some reason I'm calling the function with a `pandas dataframe`, but FeatureWiz seems to be assuming a `dask dataframe`. 

```
                output = FW.featurewiz(df, col, corr_limit=0.70, verbose=2, sep=',', header=0
                                       , test_data='', feature_engg='interactions', category_encoders=''
                                       , dask_xgboost_flag=True, nrows=1000)
```
I also attach the first few rows of the input dataframe, though it might not be the data that is causing this issue - I've also tried to run an identical script with the same data on another remote machine, yet it doesn't show this error.

Both are running a virtualenv in WSL Ubuntu 20.04 , though there are likely some slight differences in the installed packages.

[error_sample.zip](https://github.com/AutoViML/featurewiz/files/7847191/error_sample.zip)

**Comment by AutoViML** [comment]
Hi @zw10 👍 
One very simple trick: just set `dask_xgboost_flag` = 'False` in your calling statement and try running it. That might avoid the dask error. If that works, all the best.
AutoViML

**Comment by zw10** [comment]
Thank you - confirming that the fix is working as intended, after the upgrade to v0.81

And `dask_xgboost_flag='False'` works for v0.80
