### ISSUE TITLE
How to enable GPU support?

### ISSUE THREAD

**Issue by zw10** [AutoViML/featurewiz#13]
Thanks again for this package! Though I do have an active GPU on the device, it doesn't seem to be detected. Is there some way of enabling GPU acceleration (and would it be useful)? 

```
No GPU active on this device
    Tuning XGBoost using CPU hyper-parameters. This will take time...
```

**Comment by zw10** [comment]
Found that this issue stems from further upstream with WSL not detecting the GPU - so closing the thread for now

**Comment by arturdaraujo** [comment]
Did you manage to use the gpu on WSL @zw10 ? I'm having the same issue
