### ISSUE TITLE
Getting error:  '<' not supported between instances of 'int' and 'str'

### ISSUE THREAD

**Issue by rohitnarain24** [AutoViML/featurewiz#14]
Hi I am trying to run a dataset which is having around 800000 rows and 42 columns but I am getting this error. given below:

TypeError                                 Traceback (most recent call last)

<ipython-input-35-3fd7aae0dd76> in <module>()
     43                                     Add_Poly=0, Stacking_Flag=False,
     44                                     Imbalanced_Flag=True,
---> 45                                     verbose=1)
     46 
     47 

4 frames

<__array_function__ internals> in unique(*args, **kwargs)

/usr/local/lib/python3.7/dist-packages/numpy/lib/arraysetops.py in _unique1d(ar, return_index, return_inverse, return_counts)
    320         aux = ar[perm]
    321     else:
--> 322         ar.sort()
    323         aux = ar
    324     mask = np.empty(aux.shape, dtype=np.bool_)

TypeError: '<' not supported between instances of 'int' and 'str'

Can Anyone, Please help me which column having problem in my dataset. I am not getting any clue from error. Please help me to resolve this error

**Comment by AutoViML** [comment]
Hi @rohitnarain24 👍 
Can you please paste a small snippet of your data as a Zip file here?  I cannot trouble shoot the code without knowing why and where it is erroring. Can you please also post the version number of the library and the calling statement?

Thanks so much
AutoViML

**Comment by rohitnarain24** [comment]
[sample_data.zip](https://github.com/AutoViML/featurewiz/files/7931862/sample_data.zip)

Hi,

Thank you for reviewing my problem, as a response please find herewith the sample data that I have tried, for now I am sharing 100 rows with 34 columns data but I am trying with around 44K rows data.
The version of AutoViML : 0.1.684

The piece of code I am trying is given below:


size = int(0.7*merged_data.shape[0])
train_df = merged_data[:size]
test_df = merged_data[size:]

target='Target_variable'

# # #-----------------------Auto ML Model---------------------
model, features, trainm, testm = Auto_ViML(train_df, target, test_df, sample_submission='',
                                    scoring_parameter='',
                                    hyper_param='RS',feature_reduction=True,
                                     Boosting_Flag=True,Binning_Flag=False,
                                    Add_Poly=0, Stacking_Flag=False, 
                                    Imbalanced_Flag=True, 
                                    verbose=1)

**Comment by AutoViML** [comment]
Hi @rohitnarain24 👍 
I am not getting an error at all. I found that the code works well on the 100 row sample dataset except in the end where it is trying to compare actuals and predictions (see my notebook attached as a zip file).
[AutoVIML_Test_Sample_Data.zip](https://github.com/AutoViML/featurewiz/files/7964157/AutoVIML_Test_Sample_Data.zip)

Take  a look and see if you can copy the results.

If not, Can you please copy and paste the screenshot of where AutoViML is erroring. I need the exact line in AutoViML and the error message. 
Sorry for the trouble.
AutoViML
