### ISSUE TITLE
Not able to replicate results - seed not set for random

### ISSUE THREAD

**Issue by chrico-bu-uab** [AutoViML/featurewiz#15]
This issue was raised previously and was said to have been addressed but I am still getting inconsistent results.

I checked the source code. Seeds are provided for numpy's and others' random number generators but not for package random.

Can this please be fixed ASAP? Thank you so much.

**Comment by AutoViML** [comment]
Hi @chrico-bu-uab 👍 
You are absolutely correct! There was one place where the seed was not set. I have fixed it.

Plead do:

```pip install featurewiz --upgrade```

You should see version 0.0.84 and that should be fixed.
Enjoy
AutoViML
