### ISSUE TITLE
UnboundLocalError: local variable 'params' referenced before assignment

### ISSUE THREAD

**Issue by Benno26** [AutoViML/featurewiz#16]
/opt/conda/lib/python3.7/site-packages/featurewiz/featurewiz.py in featurewiz(dataname, target, corr_limit, verbose, sep, header, test_data, feature_engg, category_encoders, dask_xgboost_flag, nrows, **kwargs)
   1130         param['nthread'] = -1
   1131         param['tree_method'] = 'gpu_hist'
-> 1132         params['eta'] = 0.01
   1133         params['subsample'] = 0.5
   1134         params['grow_policy'] = 'depthwise' # 'lossguide' #

Is params getting set here instead of param? https://github.com/AutoViML/featurewiz/blob/main/featurewiz/featurewiz.py

**Comment by Benno26** [comment]
Thought as much, thanks for the quick fix :)

**Comment by AutoViML** [comment]
Fixed. Closed

**Comment by a-schot** [comment]
This issue returned. I tried version 0.3.0 and 0.3.1
```
UnboundLocalError                         Traceback (most recent call last)
[<ipython-input-7-5c3d00237eee>](https://localhost:8080/#) in <cell line: 1>()
----> 1 X_train_selected = fwiz.fit_transform(X_train, pd.Series(y_train, name="status_group"))
      2 X_test_selected = fwiz.transform(X_test)
      3 ### get list of selected features ###
      4 fwiz.features

3 frames
[/usr/local/lib/python3.10/dist-packages/featurewiz/featurewiz.py](https://localhost:8080/#) in featurewiz(dataname, target, corr_limit, verbose, sep, header, test_data, feature_engg, category_encoders, dask_xgboost_flag, nrows, skip_sulov, **kwargs)
    758         param['nthread'] = -1
    759         param['tree_method'] = 'gpu_hist'
--> 760         params['eta'] = 0.01
    761         params['subsample'] = 0.5
    762         params['grow_policy'] = 'depthwise' # 'lossguide' #

UnboundLocalError: local variable 'params' referenced before assignment
```
