### ISSUE TITLE
Featurewiz key error during fit and transform

### ISSUE THREAD

**Issue by SSMK-wq** [AutoViML/featurewiz#18]
I am working on a ML project to select important features.

So, I am using the `Featurewiz` package from documentation [here][1]

I tried the below from github for my data

    from featurewiz import FeatureWiz
    features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False, nrows=None, verbose=2)
    X_train_selected = features.fit_transform(ord_train_t, y_train)
    X_test_selected = features.transform(ord_test_t) # error is encountered here
    features.features  ### provides the list of selected features ###

Both `ord_train_t` and `ord_test_t` contain the same columns.

But I get a key error message when I try to use `transform` function after `fit`.

  `  KeyError: "['Feat1', 'Feat2', 'Feat3', 'Feat5', 'Feat6', 'Feat7'] not in index"`

But these columns are present in my `ord_test_t` data.

Is there anything wrong with the package or documentation? \

or am I using the `fit` and `transform` functions incorrectly?

find the full error below

```
    C:\Users\abcd\AppData\Local\Temp/ipykernel_11076/432759899.py in <module>
          2 features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False, nrows=None, verbose=2)
          3 X_train_selected = features.fit(ord_train_t, y_train)
    ----> 4 X_test_selected = features.transform(ord_test_t)
          5 features.features  ### provides the list of selected features ###
    
    ~\Anaconda3\lib\site-packages\featurewiz\featurewiz.py in transform(self, X)
       3562 
       3563     def transform(self, X):
    -> 3564         return X[self.features]
       3565 ###################################################################################################
       3566 import copy
    
    ~\Anaconda3\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
       3462             if is_iterator(key):
       3463                 key = list(key)
    -> 3464             indexer = self.loc._get_listlike_indexer(key, axis=1)[1]
       3465 
       3466         # take() does not accept boolean indexers
    
    ~\Anaconda3\lib\site-packages\pandas\core\indexing.py in _get_listlike_indexer(self, key, axis)
       1312             keyarr, indexer, new_indexer = ax._reindex_non_unique(keyarr)
       1313 
    -> 1314         self._validate_read_indexer(keyarr, indexer, axis)
       1315 
       1316         if needs_i8_conversion(ax.dtype) or isinstance(
    
    ~\Anaconda3\lib\site-packages\pandas\core\indexing.py in _validate_read_indexer(self, key, indexer, axis)
       1375 
       1376             not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
    -> 1377             raise KeyError(f"{not_found} not in index")
       1378 
       1379 
    
        KeyError: "['Feat1', 'Feat2', 'Feat3', 'Feat5', 'Feat6', 'Feat7'] not in index"
```

  [1]: https://github.com/AutoViML/featurewiz

**Comment by AutoViML** [comment]
Please note that you need to send in dataframes as input, not numpy arrays. You may have sent in arrays when you split the data intro train and test. Please double check. This code snippet works for me.
```
from featurewiz import FeatureWiz
features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False, nrows=None, verbose=2)
X_train_selected = features.fit_transform(ord_train_t, y_train)
X_test_selected = features.transform(ord_test_t) # error is encountered here
features.features  ### provides the list of selected features ###
```
Please post your sample ord_train_t and ord_test_t data sets here for me to test out. Thanks for trying out featurewiz.
Thanks
AutoViML

**Comment by SSMK-wq** [comment]
@AutoViML My ord_train_t contains target column as well and it is a dataframe (not numpy array). Sure, will update the sample in 10 mins

**Comment by SSMK-wq** [comment]
@AutoViML - My `ord_train_t` is a dataframe. my `y_train` is also a dataframe, my `ord_test_t` is also a dataframe. please help me.

Please find below the sample data. I can't share original data due to confidentiality reasons. But I can say that most of my columns are ordinally encoded (except 4 columns).

ord_train_t

```
Feat1  Feat2    Feat3      Feat4    Feat5   Feat6  Feat7
2          13        1200         1          0          0         1
1          56        3800         1          2          0         23
4          59       1356000    3          8          0         27
3          31        56568       4          3          2         38
2          27        217863     6          5          2         32
```
ord_test_data

```
Feat1  Feat2      Feat3      Feat4    Feat5   Feat6   Feat7
21         113        12100         1          0          0     101
11         156        38100         1          2          0     220
40         519       13500          3          8          0      12
33          311        568            4          3          2      14
21          217        7863          6          5          2       36

**Comment by SSMK-wq** [comment]
@AutoViML  - Hope this sample data useful for you to test.

**Comment by AutoViML** [comment]
Hi @SSMK-wq 👍 
I have attached your dataset and my notebook to test it. There was no error at all. Can you please download this and use it in your laptop. 
[All_Main.zip](https://github.com/AutoViML/featurewiz/files/8112794/All_Main.zip)
please download it and test it
Thanks
AutoViML

**Comment by SSMK-wq** [comment]
@AutoViML  - I am sorry. For some reason that I am not sure why, I still get the same key error when I pass in ordinally encoded dataframes as input. Meaning,my `fit` function works well. It's only my `transform` on test data fails with key error. But my test data also has the same columns as train data. Anyway, I also understand for you it works fine. Am not sure, how can this be reproduced to solve this issue. Thanks for your help anyway. I will try it out manually.

**Comment by SSMK-wq** [comment]
Oh, I think I found what is the issue now. I think the package fills the spaces in column names with underscores. Meaning if my original column name is `product group`, the package converts them to `product_group` (with underscore in between). This prevents from transforming.

**Comment by AutoViML** [comment]
Hi @SSMK-wq 👍 
I think you caught a nice bug! thanks for bringing it to my attention. I will be uploading a new version 0.1.01

Please upgrade to it via:
```
pip install featurewiz --upgrade
```

You should be able to see that fit and transform work correctly now even if the column names are changed.

Thanks
AutoViML
