### ISSUE TITLE
[FEATURE REQUEST] - Limit the use of feature selection until SULOV part

### ISSUE THREAD

**Issue by fjpa121197** [AutoViML/featurewiz#23]
Hello,

I was wondering if there could be a way to limit the automated feature selection part until after SULOV?

I'm trying to only get the output from removing low variance features and correlated features. Is this possible? I dont want to run the recursive XGBoost feature selection part.

Not sure if it is allow to change the code in my conda environment, and add a flag that returns the `final_list` variable after running SULOV?

**Comment by AutoViML** [comment]
Hi @fjpa121197 👍 
There is actually an easier way. featurewiz uses the following function to remove variables using the SULOV method. You can call it yourself.

```
import featurewiz as FW
outputs = FW.FE_remove_variables_using_SULOV_method(df, numvars, modeltype, target, corr_limit=0.7, verbose=0, dask_xgboost_flag=False)
```
You must send only df which is a dataframe and numvars which is a list of numeric variables in that dataframe, along with modeltype which is either 'Regression' or 'Classification' and target which is the name of the target variable. The rest you can leave as is or modify as needed.

Hope this helps
AutoViML

**Comment by fjpa121197** [comment]
Thanks a lot!
