### ISSUE TITLE
saving transformers?

### ISSUE THREAD

**Issue by asimovidick** [AutoViML/featurewiz#24]
Is it possible to save all data transformers used during feature selection in order to apply them to a new dataset?
If yes, what could be the process and how to reuse them?

Thanks a lot.
Your work is amanzing, have to say

**Comment by fjpa121197** [comment]
They recently included the feature to use Featurewiz as a scikit-learn compatible transformer. 

From their documentation, the following examples shows how to use it:

```python
from featurewiz import FeatureWiz
features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', dask_xgboost_flag=False, nrows=None, verbose=2)
X_train_selected = features.fit_transform(X_train, y_train)
X_test_selected = features.transform(X_test)
features.features  ### provides the list of selected features ###
```

You can save the `feature` object using pickle (I think)  and then use it with new data.

**Comment by asimovidick** [comment]
That was really great! Thanks!! @fjpa121197
