### ISSUE TITLE
Error--Some features created with datetime column are not in the index.

### ISSUE THREAD

**Issue by saikiran1201** [AutoViML/featurewiz#26]
https://www.kaggle.com/pasuvulasaikiran/netflix-featurewiz

link to the kernel.

**Comment by AutoViML** [comment]
Hi @saikiran1201 👍 

Thanks for testing out featurewiz. I have now fixed the problem and it runs fine with date-time features.
```
!pip install featurewiz --upgrade
```
Thanks
AutoViML

**Comment by saikiran1201** [comment]
Thank you for the quick fix. 
One more issue I noticed is that features.features not returning the list of selected features instead it returns predictions of the target.

**Comment by AutoViML** [comment]
Hi @saikiran1201 👍 
I have fixed that too. Please confirm. Upgrade via:
```
!pip install featurewiz --upgrade
```
Thanks
AutoViML

**Comment by saikiran1201** [comment]
Still features.features not returning the list of selected features. Its an empty list now.
