### ISSUE TITLE
Cannot find example .csv files

### ISSUE THREAD

**Issue by blhall195** [AutoViML/featurewiz#28]
Hi, I'm trying to use one of your example test scripts 

https://github.com/AutoViML/featurewiz/blob/main/examples/FeatureWiz_Test.ipynb

but I can't find the breast_cancer.csv file. Any chance you could add them to the repo?

**Comment by AutoViML** [comment]
Hi @blhall195 👍 
Next time, try Google search:
https://www.google.com/search?client=firefox-b-1-d&q=breast-cancer+csv+file
AutoViML

**Comment by blhall195** [comment]
Thanks :)
