### ISSUE TITLE
Question on nlp columns

### ISSUE THREAD

**Issue by asimovidick** [AutoViML/featurewiz#29]
Just a question
When a column in a dataset is considered nlp and when a categorical one?

I found this condition in your code:
```
def classify_columns(df_preds, verbose=0):
...

if train[col].map(lambda x: len(x) if type(x)==str else 0).mean(
                ) >= max_nlp_char_size and len(train[col].value_counts()
                        ) <= int(0.9*len(train)) and col not in string_bool_vars:
                var_df.loc[var_df['index']==col,'nlp_strings'] = 1

```

I wonder if it has not to be:

`>= int(0.9*len(train)) `

Thanks,
Cheers

**Comment by AutoViML** [comment]
Hi @asimovidick 👍 
I think it was a mistake. You can create a Pull Request if you want for that change and I will accept it. That way, you will get credit for this contribution!
Thanks
AutoViML

**Comment by asimovidick** [comment]
Hi,
It does not matter, just wanted to know if my "finding" was correct or not.
Your job is amazing, really.
Thanks
Best
