### ISSUE TITLE
TypeError: gen_cat_encodet_features() got an unexpected keyword argument 'fitted'

### ISSUE THREAD

**Issue by bbanzai88** [AutoViML/featurewiz#33]
Hi,
I love featurewiz!! I got it to work using:

#outputs = featurewiz(df99, target='FSXRNE', corr_limit=0.70, verbose=2,
#header=0, test_data='',feature_engg='interactions')

and it worked really well! HOwever, when I use:

outputs = featurewiz(df99, target='FSXRNE', corr_limit=0.70, verbose=2,header=0, category_encoders='OneHotEncoder')

I get: 

TypeError: gen_cat_encodet_features() got an unexpected keyword argument 'fitted'

Any ideas on what is going wrong? Thank you!

Sincerely,

tom

**Comment by AutoViML** [comment]
Hi @bbanzai88 👍 
There seems to be someth8ing wrong here in your machine. I am getting perfect results when I use the latest version 0/.1.43 by:
```
pip install featurewiz --upgrade --ignore-installed --no-deps
```
Thanks
AutoViML
<a href="https://ibb.co/3B5CSyr"><img src="https://i.ibb.co/wMZzpN0/featurewiz-screenshot.png" alt="featurewiz-screenshot" border="0"></a>
