### ISSUE TITLE
Add package to conda-forge

### ISSUE THREAD

**Issue by arturdaraujo** [AutoViML/featurewiz#34]
It would be great to see featurewiz to conda-forge. Some packages rely only on conda distirbution so other packages distritbutions don't get messed up. I'm not that familiar using github (in fact this is my first time creating an issue). 

https://conda-forge.org/#add_recipe
https://github.com/conda-forge/staged-recipes
https://github.com/conda-incubator/grayskull

**Comment by arturdaraujo** [comment]
I'm implementing that feature... It might be available soon to install using conda install -c conda-forge featurewiz

**Comment by arturdaraujo** [comment]
DONE! Congrats on the package, it's on conda-forge now.
https://anaconda.org/conda-forge/featurewiz

**Comment by AutoViML** [comment]
Thank you so much for doing such a great job @arturdaraujo !!
