### ISSUE TITLE
feature_engg is not working properly

### ISSUE THREAD

**Issue by satwiksunnam19** [AutoViML/featurewiz#35]
I'm trying to use this but it's showing an error when I'm using the "feature_eng" parameter used. I'm attaching some screenshots please help me with this. when I'm using that parameter it's showing that the new features that were added by featurewiz is not find in original dataset.
![image](https://user-images.githubusercontent.com/83942187/174857806-8738aa6a-6e28-40dc-8293-d414f99da186.png)
![image](https://user-images.githubusercontent.com/83942187/174858504-00d11a0c-4e7a-4004-9512-039c0a0223cd.png)
![image](https://user-images.githubusercontent.com/83942187/174858613-5e4bc54f-99da-419d-8c41-9cac1f104378.png)

**Comment by AutoViML** [comment]
Hi @satwiksunnam19 👍 
Sorry you had an error while trying out featurewiz. There is a difference in syntax between featurewiz's tow main goals: one is for feature selection and the other is for feature_engg. You have selected the wrong syntax for feature_engg. The syntax you should choose is:
```
trainm, testm = FW.featurewiz(dataname=train, target=target, corr_limit=0.70, verbose=2, sep=',', 
		header=0, test_data=test, feature_engg='', category_encoders='',
		dask_xgboost_flag=False, nrows=None)
```

If you try the above syntax you will get feature_engg and feature selection done right.
Hope this helps. I will update the README file later. If you have the time, you can update it and submit a Pull Request.
Thanks
AutoViML
