### ISSUE TITLE
Memory Runout Error for even less memory of dataset when using Featurewiz

### ISSUE THREAD

**Issue by satwiksunnam19** [AutoViML/featurewiz#38]
I have a dataset whose memory is around (440.06 MiB) training data and test data (219.6 MiB) when I try to use the featurewiz with this dataset it's showing an error of memory run out on GPU (Kaggle and Google colab) 
1. Is there any method to solve this problem, rather than going to cloud platforms?
2. Is there any method to free the space when working with featurewiz internally in the codes of featurewiz?
3. I have loaded the dataset into the GPU environment and loaded those direct data frames into fearurewiz showing an error.
![image](https://user-images.githubusercontent.com/83942187/175331745-40a2524e-bdc4-4e2e-908e-eb51273a1bf3.png)
![image](https://user-images.githubusercontent.com/83942187/175331996-3fac875d-11bc-4d95-9871-5b1e92a8489e.png)
![image](https://user-images.githubusercontent.com/83942187/175332084-ac1def2c-573d-49c7-8d65-0fa86e4e83e6.png)
Dataset can be found at "https://www.kaggle.com/competitions/ventilator-pressure-prediction/data"

**Comment by AutoViML** [comment]
Hi @satwiksunnam19 👍 
Thanks for trying out featurewiz on large datasets. Unfortunately, you cannot beat the memory limitations of pandas.Hence you need to downsample your training data to fit featurewiz by taking may be using 10% of your data to find the best features. 

Secondly, I would not recommend that you do feature engg to generate more features in a time series data set like that one. It is not likely to help you much. That's my advice.
Thanks
AutoVimal
