### ISSUE TITLE
Columns must be same length as key

### ISSUE THREAD

**Issue by Milad-abbaszadeh** [AutoViML/featurewiz#40]
Hi there, 
I am new to featurewize and I have got a wired error while I am using it. It happened after feature selection got completed. 
I have followed the instruction and I am getting the following error. 
I would be really grateful if anyone can help me. 
Thanks in advance
![image](https://user-images.githubusercontent.com/30858269/179239155-2235e141-d8c4-4e98-926c-cd626f5a0642.png)

**Comment by AutoViML** [comment]
Hi @Milad-abbaszadeh 👍 
It seems you have a slightly old version of Featurewiz where this error happened. Can you please upgrade to the latest version by:

```
pip install featurewiz -- upgrade
```
or
```
 conda install -c conda-forge featurewiz
```
If you see the latest version (0.1.91) printed when you import featurewiz then yhou are working on the best version.
If that doesn't fix it, please report back here with some link to the dataset or the colab notebook where I can take a look at it.

AutoVimal

**Comment by Milad-abbaszadeh** [comment]
Hi AutoVimal, 
Thanks for your quick reply.
It seems you are using an old version of the scikit-learn. trying to upgrade the package.

`The conflict is caused by:
    featurewiz 0.1.91 depends on scikit-learn~=0.24
    category-encoders 2.4.0 depends on scikit-learn>=0.20.0
    imbalanced-ensemble 0.1.7 depends on scikit-learn>=1.0`

**Comment by Milad-abbaszadeh** [comment]
update : 
the source of the python versioning conflict is in the`[ requirement files ](https://github.com/AutoViML/featurewiz/blob/main/requirements.txt)`
in this file you need a imbalanced-ensemble 0.1.7 and it needs a scikit-learn>=1.0 while in the other part of the requirement.txt you need scikit-learn~=0.24. I think this is the root of problem.

**Comment by AutoViML** [comment]
Ok thanks - I know these conflicts. But if you can  check out these Kaggle notebooks where I show you how to use featurewiz, it will be great. That way, you can use CPUs and GPUs to run featurewiz. It also shows you how to run with these so-called conflicts.
1. Netflix Appetency competition using featurewiz
2. https://www.kaggle.com/code/rsesha/netflix-appetency-featurewiz-privatescore-0-78
3. https://www.kaggle.com/code/rsesha/tps-june-featurewiz-score-0-899-in-10-lines
Please take a look and try colab or Kaggle.
