### ISSUE TITLE
Why test has not target and how to use model to make predict

### ISSUE THREAD

**Issue by sunxuen** [AutoViML/featurewiz#41]
hello,
I have three questions:
1:  When  I use  train, test = FW.featurewiz() , i find test return have not encoded target,but I need recalculate balanced_accuracy_score that need encoded target, so I add target in return, Is this correct？
![image](https://user-images.githubusercontent.com/38027301/179388675-5478210f-15d2-469f-8dc3-1a96f89d250d.png)

2: How to use fitted model to predict? I get outputs[-1] as fitted model, but its predictions is all 1, its not the same as outputs[0]。This is my code, am I using it wrong? By the way ,Can you provide some examples for using simple_LightGBM_model ,simple_XGBoost_model, etc.
![image](https://user-images.githubusercontent.com/38027301/179389125-1ad7325c-5f11-41f1-8b55-9cd8654cfb7d.png)

3: When I use  fitted model to predict raw data, how can I get transformer for raw data? 

Hope to get your reply，thanks!

**Comment by AutoViML** [comment]
Hi @sunxuen 👍 
Answers to your 3 questions below.
1. Based on the screenshot of the code, you are not using the latest version of "featurewiz". Can you please try upgrading via:
`pip install featurewiz --upgrade```
2.  Here is an example of how to use the simple and complex lightGBM models:
https://www.kaggle.com/code/rsesha/netflix-appetency-featurewiz-privatescore-0-78
3. Re: transformer of raw data, you need to use the latest syntax of featurewiz:
```
from featurewiz import FeatureWiz
features = FeatureWiz(corr_limit=0.70, feature_engg='', category_encoders='', 
dask_xgboost_flag=False, nrows=None, verbose=2)
X_train_selected = features.fit_transform(X_train, y_train)
X_test_selected = features.transform(X_test)
```

Hope this helps,
Autovimal

**Comment by sunxuen** [comment]
@AutoViML  Thanks  your reply, but I still feel confused about third question. Here is my code:
![7A562508-FC0D-4074-B977-E72A7EEE5F71](https://user-images.githubusercontent.com/38027301/179705978-7791f2d2-1b0a-476e-837a-d5041b5d759e.png)

![C6499442-6C5B-4569-A588-07681D410234](https://user-images.githubusercontent.com/38027301/179706135-5f0e183e-be8f-433e-8a54-bd92c6edd22f.png)

I want to save fitted xgb model for predict raw data, but the return of features.transform(X_test) is unencoded. So I have to write my sklearn pipeline transform for raw data according to data_transforn function?
lastly, Can you check my code for simplifications based on featurewiz?
Thanks!

**Comment by AutoViML** [comment]
Hi @sunxuen 👍 
We have created an easy library to transform your data. First transform it using "lazytransform" on this GitHub site and then use featurewiz. Both of them are sklearn compatible pipelines and you can use them interchangeably.

```
pip install lazytransform
```
