### ISSUE TITLE
Featurewiz cannot be used on Google Club

### ISSUE THREAD

**Issue by ooghry** [AutoViML/featurewiz#43]
Featurewiz needs networkx>=2.8.1 which need Python >= 3.8 and Google Colab has python 3.7.

**Comment by AutoViML** [comment]
Hi @ooghry 👍 
Thanks for trying out Featurewiz. I have a Colab here which works fine if you follow these steps carefully as outlined here and in the Github.

https://colab.research.google.com/drive/1ekBZgCDgRGJU25unwZ0lvla_k20pq36h?usp=sharing

```
!pip install featurewiz --ignore-installed --no-deps
!pip install 'fsspec>=0.3.3'
!pip install category_encoders --upgrade
!pip install imbalanced_ensemble
```

Once you do the above, it works like a charm.
Autovimal
