### ISSUE TITLE
Verbose

### ISSUE THREAD

**Issue by quaid281** [AutoViML/featurewiz#45]
Fantastic and beautiful package.  

is it possible I could run this package on a list of dataframes without having to close graphs even when I set verbose to 0?

**Comment by AutoViML** [comment]
Hi @quaid281 👍 
Thanks for trying out featurewiz. spread the word!
I have now fixed verbose so that when `verbose=0` it is mostly silent and no graphs or charts are displayed. Try it out and let me know.

```
pip install featurewiz --ignore-installed --no-deps --upgrade
```

Thanks
Autovimal

**Comment by quaid281** [comment]
Hey AutoViML, I never had a chance to say thank you.  Every thing is working amazing now.
