### ISSUE TITLE
cannot replicate feature selection result

### ISSUE THREAD

**Issue by teetysasithorn** [AutoViML/featurewiz#5]
Is there a way to keep the feature selection result the same for every times I run? I tried to run the function and it's giving me different result for each time.

Original data - 365 variables
1st run - select 87 variables
2nd run - select 82 variables

**Comment by AutoViML** [comment]
Hi @teetysasithorn 👍 
I have made a lot of changes - increasing the performance of dask by orders of magnitude. It also should be consistent in results now.

Can you please upgrade to the latest version?

pip install featurewiz --upgrade

Thanks
AutoViML

**Comment by chrico-bu-uab** [comment]
Unfortunately I also am still having reproducibility issues when running with default params plus feature engineering for interactions and groupby.

**Comment by AutoViML** [comment]
I have fixed the random_seed for both numpy and random libraries at the top of the featurewiz library. I thought that fixed it long ago. I am not sure if you are running with the latest version.Try upgrading to the latest version and see.

    On Friday, July 7, 2023 at 02:43:57 PM EDT, Chris Coffee ***@***.***> wrote:  
 
 


Unfortunately I also am still having reproducibility issues when running with default params plus feature engineering for interactions and groupby.
