### ISSUE TITLE
Featureviz for data with "No Target" Variable

### ISSUE THREAD

**Issue by sriprad** [AutoViML/featurewiz#52]
Hi Team,

Thank you for creating this great library. I would like to know how can i modify the code to use it for my data which doesn't have Target or predictor. Like unsupervised data and i wanted to reduce the dimension of the techniques.

Please let me know,

**Comment by AutoViML** [comment]
Hi @sriprad 👍 
This is a good idea but currently have no plans to do this. If you have some time to research what methods are best and recommend a link or implementation, then I would be happy to incorporate it. This can be a pull request by you as well.
AutoVimal
