### ISSUE TITLE
Prevent shuffling of data throughout featurewiz

### ISSUE THREAD

**Issue by markdregan** [AutoViML/featurewiz#54]
Is it possible to prevent data shuffling throughout the featurewiz process?

My data has a temporal component (time series effectively) and shuffling doesn't make sense. 

Perhaps there is a parameter already I can use to disable shuffling?

Thanks fro a great library.

**Comment by AutoViML** [comment]
Hi @markdregan:
This is a good question. 👍 

I have now disabled shuffling for all Regression and TimeSeries problems. So if your target variable is float, then you should see that the order of rows is preserved. Please upgrade version 0.1.993 via:
```
 !pip install featurewiz --ignore-installed --no-deps --upgrade
```
Then you can try it  and if it works, close this issue!
AutoVimal

**Comment by markdregan** [comment]
Thanks for the quick response and fix. 👍
