### ISSUE TITLE
Using SULOV and iterative xgboost separately

### ISSUE THREAD

**Issue by sokol11** [AutoViML/featurewiz#57]
Hi. Perhaps a naive question: is there a way to suppress SULOV or iterative xgboost when calling featurewiz? This could be useful for benchmarking one against the other or one vs both, i.e. maybe SULOV alone is sufficient, or maybe iterative xgboost is sufficient for a particular use case, while also being significantly faster than using both. In my use case, I have a cross-validation pipeline with a lot of splits, so I'm interested in minimizing the feature selection time for each split and would like to know how much the performance would degrade if I only use one algorithm (SULOV or xgboost) and how much faster it would be. This seems like it should be a trivial modification to existing code / interface, if it's not already there. Thank you!

**Comment by AutoViML** [comment]
@sokol11 I think it's a good suggestion 👍 

I have implemented it as follows: You can skip SULOV now with a ski_sulov flag added to the input. See the main [README](https://github.com/AutoViML/featurewiz) page for documentation. If you want to perform just SULOV you can use the function in featurwiz called `FE_remove_variables_using_SULOV_method()` . That should do the trick.

I did not have the time break them out into separate transformers, etc. That would take too much time and I leave it to someone to do it and submit a pull request if they can.

hope this helps,
Ram

**Comment by sokol11** [comment]
Thanks, that's very helpful!
