### ISSUE TITLE
results change between same run

### ISSUE THREAD

**Issue by sungla55guy** [AutoViML/featurewiz#59]
results for the same data between runs produces a different list of features.  Is there an issue with random_state not being set somewhere?

**Comment by sungla55guy** [comment]
This happens during SULOV, the number of features removed between runs with the same data changes between runs

**Comment by AutoViML** [comment]
Hi @sungla55guy
Thanks for trying out featurewiz 👍 

I have been trying very hard to get this fixed but it's a bit tricky. I think I have finally fixed it. But please upgrade to the latest version 2.03 and test it out. 👍 

`pip install features --upgrade --no-deps --ignore-installed`

thanks again
AutoViML
