### ISSUE TITLE
Were you planned to drop duplicated correlation coefficients?

### ISSUE THREAD

**Issue by such3r** [AutoViML/featurewiz#60]
https://github.com/AutoViML/featurewiz/blob/a7933245cdbc6c603af8bb9dd292357fb5a00e04/featurewiz/sulov_method.py#L90

Consider putting this in the following:
`correlation_dataframe = df.corr().abs().unstack().sort_values().round(7).drop_duplicates()`

Note `.round(7)` had been added before `.drop_duplicates()`. Since we can have multiple values close to unity or zero. For some problems round decimals can be even smaller then 7.

**Comment by AutoViML** [comment]
Hi @such3r
Thanks for testing out featurewiz 👍 

I liked your suggestion and changed the code. Please upgrade to the latest version and try it again.
Thanks
AutoVimal

**Comment by Harry040** [comment]
why use `drop_duplicates`? that will drop  features with 0 corr

**Comment by AutoViML** [comment]
Hi @Harry040 
Thanks for picking up on this thread. But I tested it on multiple dataframes and  I have not seen it happen yet. Can you provide a code sample  where this would impact as you suggesting?
Thanks
Auto Vimal
