### ISSUE TITLE
Question about feature selection with small dataset

### ISSUE THREAD

**Issue by agt64** [AutoViML/featurewiz#62]
I created a simple df with only 5 rows, 6 columns including a target "survived". The data was made in such a way that all "Female" from the gender variable survive. Thus I would expect "gender" to be returned as an important feature. However it produces "Selected 0 important features". Why is that? 

Code below:

import featurewiz as FW
import pandas as pd

df = pd.DataFrame({'id': [1, 2, 3, 4, 5],
                   'name': ['Alice', 'Bob', 'Charlie', 'Dave', 'Eve'],
                   'gender': ['Female', 'Male', 'Male', 'Male', 'Female'],
                   'age': [25, 30, 35, 40, 45],
                   'income': [50000, 55000, 60000, 65000, 70000],
                   'survived': [1, 0, 0, 0, 1]})

target = 'survived'

out1, out2 = FW.featurewiz(dataname=df, target=target, corr_limit=0.7, verbose=2, sep=',', 
		header=0, test_data='',feature_engg='', category_encoders='',
		dask_xgboost_flag=False, nrows=None)

**Comment by AutoViML** [comment]
Sorry I fail to understand. Do you think real world datasets have 5 samples? Try to increase the sample size to your realistic needs.

**Comment by agt64** [comment]
No worries ty! I was using sequential forward selection as a baseline and it was able to identify the correct features. Haven't tested this on larger datasets, but for my purposes ideally I need it to work on both small and large datasets.
