### ISSUE TITLE
Pyarrow Dependency Conflict

### ISSUE THREAD

**Issue by curtisraymond** [AutoViML/featurewiz#63]
I'm receiving a dependency conflict since featurewiz has a hard **pyarrow=7.0.0** dependency requirement and cudf has a **pyarrow>=9.0.0** dependency requirement. Would it be possible to change this hard  **pyarrow=7.0.0** dependency to **pyarrow>=7.0.0** instead?

**Comment by AutoViML** [comment]
Hi @curtisraymond 
Thank you for trying out featurewiz👍 

I have modified the setup.py and requirements.txt files. please check them and download them again.
regards,
AutoVimal
