### ISSUE TITLE
Featureviz  misclassify the problem 

### ISSUE THREAD

**Issue by GDGauravDutta** [AutoViML/featurewiz#64]
We don't have to tell Featurewiz whether it is a Regression or Classification problem. It will decide that automatically.

But want to overide that

**Comment by GDGauravDutta** [comment]
As part of workaround, I added a noise to target to make algo believe that it's regression

**Comment by AutoViML** [comment]
@GDGauravDutta 
Thanks for bringing this problem to my attention. This happens in some small datasets since I used heuristics to detect whether it is a classification or regression problem.
Hope you solved it yourself. Please re-open this issue if it doesn't work.
AutoVimal
