### ISSUE TITLE
"not selecting any important features since it did not meet criteria: F-score > 1.0"

### ISSUE THREAD

**Issue by EXJUSTICE** [AutoViML/featurewiz#65]
Hi,

I've a dataset with 104 features and over 90k rows for a numerical regression problem, and am working in Kaggle, using the specific installation instructions mentioned. I've bumped into the problem that FeatureWiz is claiming that none of my features  match the F-score limit required. However, running the XGB model with features definitely results in a capability to achieve an RMSE baseline. From F-Score charts, I can observe that the maximal F-score is 0.0125 for one of the XGB models.

Any help is appreciated with this, wondering if I would have to change the F-score limit somehow for this case?

**Comment by AutoViML** [comment]
Hi @EXJUSTICE : thank you for trying out featurewiz.

I don't know where the F-score limit is reached message is coming from. I need a screenshot or at least a Kaggle notebook where you are seeing that message.

Can you please add more details to help me?
Thanks
AutoVimal

**Comment by EXJUSTICE** [comment]
I'll get back to you when the competition's over in a few days with  a more detailed breakdown of the problem.

**Comment by AutoViML** [comment]
Can you post the Kaggle data set or problem that you are working on. I can look it up myself.

Auto Vimal

**Comment by AutoViML** [comment]
Hi @EXJUSTICE 
I have found the problem of F-score not selecting any features and fixed it. It  happened in some cases. Now it should be fixed.

Please test it with the new version 0.2.5 

Thanks👍 
AutoVimal
