### ISSUE TITLE
Problem with transform after Feature Engineering part

### ISSUE THREAD

**Issue by kilincali35** [AutoViML/featurewiz#67]
Hi,

I have a dataset, and I am trying to engineer some varaibles through Featurewiz package. It seems like it will be helpful, so thanks for your contribution.

But if I add this step into my pipeline, I will need to apply it to unseen data coming through our production process. So, I will need a Transform function, to have same preprocessing steps applied to this dataset, with same engineered features remaining on it. 

Currently, it will preprocess my data, create engineered features, then it will give me a dataset with only preprocessed engineered features. I will train a model with this new dataset. And it will be my production model.

But, I will need to make predictions on a completely different dataset. I will just make predictions with my best model, being used in production. To be able to do that, I need to push a dataset with same format (Same as the output of Featurewiz feature engineering, same engineered preprocessed features) 

As far as I understand, for feature engineering, we need to use an older syntax. Which seems like not compatible with sklearn Transform. So, it makes it IMPOSSIBLE to use this helpful tool in a real life situation, on a production environment. 

Am I missing something? If you have a solution to this problem I will go on using it on my production setup. But for now, it seems like not probable.

**Comment by AutoViML** [comment]
Hi @kilincali35 
Thanks for trying out featurewiz 👍 

I am aware of this problem for a while and I have a fix but I haven't uploaded this since it will be a big change. I will try to make it available in a separate library called `featurewiz_lite` or something so that this problem is solved. Let me come back to you with an answer in  a day or two.

Auto Vimal
