### ISSUE TITLE
XGB crashes

### ISSUE THREAD

**Issue by VEZcoding** [AutoViML/featurewiz#7]
I have a matrix (191,758) and it runs in to an error with featurewiz. 

```
!Current number of predictors = 569 
    Finding Important Features using Boosted Trees algorithm...
        using 569 variables...
Finding top features using XGB is crashing. Continuing with all predictors...!
```

**Comment by AutoViML** [comment]
Hi @VEZcoding 👍 
I have tuned DASK to work with XGBoost now. I have tested it with ~400 features on ~300,000 rows dataset. It now seems to work.
Please do the following:

pip install featurewiz --upgrade --user

Let me know if it works. If not let me know.
AutoViML
