### ISSUE TITLE
Can I skip the xgboost part?

### ISSUE THREAD

**Issue by ubless607** [AutoViML/featurewiz#70]
There isn't any argument option about the xgboost.

**Comment by AutoViML** [comment]
@ubless607 : thank you for trying out featurewiz. 👍 

Yes you can skip the xgboost part by simply calling the SULOV function directly. You can search for it by doing `dir(featurewiz)` when you are in a Jupyter Notebook cell. Hope this helps.

**Comment by AutoViML** [comment]
You can run the sulov part alone by using the ```from .sulov_method import FE_remove_variables_using_SULOV_method``` function.It will run once you find how to feed it inputs using the help function.Hope this helpsAuto Vimal
    On Saturday, April 15, 2023 at 02:06:25 AM EDT, ubless607 ***@***.***> wrote:  
 
 


There isn't any argument option about the xgboost.
