### ISSUE TITLE
Number of features generated with interactions

### ISSUE THREAD

**Issue by sammekristensen** [AutoViML/featurewiz#74]
More of a question, when trying to use feature_engg='interactions' for my dataset with 129 features it creates 33000 new features and when running SULOV after it takes forever, waited for 2 hours but quit after then. Is there a way to limit the amount of new features created with interactions or is it just more suited for data sets with less features?

**Comment by AutoViML** [comment]
Hi @sammekristensen 
Thanks for trying out featurewiz 👍 

yes 33,000 features is one too many. You can first create a subset dataframe with a smaller list of columns that you want interactions for and run it through featurewiz. Once you get the features selected from there, you can add them to the main dataframe and run featurewiz but this time without interactions. This will probably be your best option.

Hope this helps,
Auto Vimal
