### ISSUE TITLE
[FR] Retrieve MIS Score / Logging

### ISSUE THREAD

**Issue by Buedenbender** [AutoViML/featurewiz#76]
Hi, 

thank you for this great package. I got a small feature request:
1. It could be very beneficial to have the option to directly log the output of `fwiz.fit_transform()` to a file on the disc, which contains, e.g., the information on the exact list of variables that had "_to be removed since ID or low-information variables_"
2. Would it be possible to return / store (in the object) the MIS score, e.g. in the process of `fit_transform()`?

**Comment by AutoViML** [comment]
Hi @Buedenbender 
Thanks for trying out featurewiz 👍 

I like your suggestion but enterprises who use open source libraries like featurewiz will not allow libraries into their enterprise if they modify files or write files to their local drive. That's a strict no-no. Hence, keeping this in mind, I am reluctant to add the logging functionality you are describing.
Let me know what you think
Auto Vimal

**Comment by Buedenbender** [comment]
Hi @AutoViML 

I totally agree about the enterprise scenario regarding FR #1. 

What do you think about FR#2: storing the metrics of feature selection (e.g., the MIS) in the featurewiz object for increased transparency? Ofc one can always compute them manually afterwards but since featurewiz takes care of preprocessing (mainly converting every Str / object to a numeric representations) there is a potential for discrepancies.

**Comment by AutoViML** [comment]
Hi @Buedenbender 
If you could create a pull request for the FR#2, I might be able to approve 👍 
Auto Vimal

**Comment by Buedenbender** [comment]
I might, but it will take me some time for sure. I am currently moving and been very busy lately
