### ISSUE TITLE
Update package

### ISSUE THREAD

**Issue by arturdaraujo** [AutoViML/featurewiz#78]
First, thanks very much for this package. I can't thank you enough.

Some updates from the dependencies of this package are already available, it would be nice to have an update.

**Comment by AutoViML** [comment]
Are you referring to any Pull Request you have made or some other updates? Can you please make it clearer?Ram    On Wednesday, September 6, 2023 at 11:32:22 PM EDT, arturdaraujo ***@***.***> wrote:  
 
 


First, thanks very much for this package. I can't thank you enough.

Some updates from the dependencies of this package are already available, it would be nice to have an update.

**Comment by arturdaraujo** [comment]
Have you contemplated using some validation dataset for tuning the features selected?

This way it is possible to select the features that are more representative of the real target on the test dataset.

**Comment by AutoViML** [comment]
Hello: Thanks for the suggestion. But I have a doubt.
The way recursive XGBoost algorithm works is by sampling features multiple times. If you want more than that, it will take a longer time to run and may be redundant. 
Has someone tested to see if your suggested approach is better than featurewiz' current approach? Can you provide some proof?
ThanksAuto Vimal
    On Tuesday, September 12, 2023 at 05:19:23 PM EDT, arturdaraujo ***@***.***> wrote:  
 
 


Have you contemplated using some validation dataset for tuning the features selected?

This way it is possible to select the features that are more representative of the real target on the test dataset.

**Comment by AutoViML** [comment]
I have added a cross_validate.py which shows how to cross-validate features selected using featurewiz. Take a look and see if it is what you are looking for.featurewiz/examples/cross_validate.py at main · AutoViML/featurewiz


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
featurewiz/examples/cross_validate.py at main · AutoViML/featurewiz

Use advanced feature engineering strategies and select best features from your data set with a single line of co...
 |

 |

 |



Auto Vimal

    On Thursday, October 5, 2023 at 12:33:20 PM EDT, arturdaraujo ***@***.***> wrote:  
 
 


Closed #78 as completed.
