### ISSUE TITLE
‘DataFrame’ object has no attribute ‘append’

### ISSUE THREAD

**Issue by gps1938** [AutoViML/featurewiz#79]
pandas >=2 append method removed fave to fix code to use newer pandas

**Comment by rsesha** [comment]
I don't plan to upgrade to pandas 2.0 for a long time since too many libraries were broken with this upgrade. They need to fix pandas first to ensure it doesn't break old code.
Auto Vimal

**Comment by gps1938** [comment]
I understand. Mamba installs wiz over panda 2. I had to downgrade Panda to use your program by setting a new 
environment. Maybe a notice that the program only works with pandas less than 2.0 should be given so the proper downgrades will be noted in a mamba/conda setting.
