### ISSUE TITLE
wiz.tarnsform returns the same data as the train for test

### ISSUE THREAD

**Issue by alienscientist** [AutoViML/featurewiz#80]
Here is the code I used,
- wiz = fwiz.FeatureWiz(corr_limit=0.70, feature_engg=['interactions', "groupby", "target"], category_encoders='', dask_xgboost_flag=False, skip_sulov=False, skip_xgboost=False, nrows=None, verbose=2)
- X_train_selected = wiz.fit_transform(X_train, y_train)
- X_test_selected = wiz.transform(X_test)

While X_test data is a different data, wiz.transform(X_test) returns the same data as X_train_selected. 
Note: I am using version 0.3.2.

**Comment by rsesha** [comment]
Hi @alienscientist 👍 
This has been fixed with the latest version 0.4.0 => please upgrade your package via:
```
pip install featurewiz --upgrade
```
