### ISSUE TITLE
Conflict Error Among Poetry Package Dependencies: lazytransform, tqdm, featurewiz

### ISSUE THREAD

**Issue by ferrotem** [AutoViML/featurewiz#84]
**Error message:**
Because no versions of lazytransform match >1.2,<1.3 || >1.3,<1.4 || >1.4,<1.5 || >1.5
 and lazytransform (1.2) depends on tqdm (>=4.61.1,<4.62.0), lazytransform (>=1.2,<1.3 || >1.3,<1.4 || >1.4,<1.5 || >1.5) requires tqdm (>=4.61.1,<4.62.0).
And because lazytransform (1.3) depends on tqdm (>=4.61.1,<4.62.0), lazytransform (>=1.2,<1.4 || >1.4,<1.5 || >1.5) requires tqdm (>=4.61.1,<4.62.0).
And because lazytransform (1.4) depends on tqdm (>=4.61.1,<4.62.0)
 and lazytransform (1.5) depends on tqdm (>=4.61.1,<4.62.0), lazytransform (>=1.2) requires tqdm (>=4.61.1,<4.62.0).
Because no versions of featurewiz match >0.4.2,<0.5.0
 and featurewiz (0.4.2) depends on lazytransform (>=1.2), featurewiz (>=0.4.2,<0.5.0) requires lazytransform (>=1.2).
Thus, featurewiz (>=0.4.2,<0.5.0) requires tqdm (>=4.61.1,<4.62.0).

**Steps to Reproduce:**
poetry add featurewiz

python = ">=3.8,<=3.10"

**Comment by ferrotem** [comment]
Thank you, your update of the tqdm requirements solved problem. 
However, there is similar problem with scikit-learn: featurewiz (>=0.4.4,<0.5.0) requires scikit-learn (>=0.24.2,<0.25.0). 
Can  you please remove upper-limit  <0.25.0 ?

**Comment by AutoViML** [comment]
Hi @ferrotem :
Sorry I cannot remove the upper limit since scikit-learn 1.0 breaks a lot of things in lazytransform. 
Auto Vimal

**Comment by ferrotem** [comment]
Hi Auto Vimal,
I am sorry, but I found out that featurewiz works well with scikit-learn 1.2.2 when we install via pip. For example, this is message during the installation: **Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.10/dist-packages (from tsfresh) (1.2.2)**
Problem occurs when I install featurewiz via poetry. Could you please explain, why there are different requirements  poetry and pip?

**Comment by AutoViML** [comment]
I have no idea about Poetry. For now, let's close this.
Auto Vimal

**Comment by Buedenbender** [comment]
@AutoViML adding to this I ran into a similar problem 
`featurewiz (0.4.4) depends on tqdm (>=4.61.1,<=4.62.0), featurewiz (>=0.4.4,<0.5.0) requires tqdm (>=4.61.1,<=4.62.0).`
The question is does featurewiz really depend on such a tight range for tqdm? Could you losen this restriction up? 
In my opinion I prefer a package being installable without version conflicts over a progressbar

**Comment by AutoViML** [comment]
Ok @ferrotem 👍 I agree and have made the changes to featurewiz requirements.txt and setup.py files. Please take a look and close it if this is what you needed.
Thanks for being patient,
Auto Vimal

**Comment by Buedenbender** [comment]
Thanks very much. Could you make a release (to pypi)? It is prohibited for my environment to install from Githuib.
