### ISSUE TITLE
Version Conflict for scikit-learn - Bump to 1.3.2 possible?

### ISSUE THREAD

**Issue by Buedenbender** [AutoViML/featurewiz#97]
Hi thank you very much for this helpful package.
Refering back to a recently successful closed ticket: https://github.com/AutoViML/featurewiz/issues/84
would it again be possible to might bump the sklearn depency to the [latest 1.3.2](https://scikit-learn.org/stable/whats_new.html)
followed by a new release of featurewiz? This would be highly appreciated.

**Comment by AutoViML** [comment]
Hi @Buedenbender 👍 
This is likely possible but I believe it will break a few things. I will test it and let you know 
If you can test it and tell me where it breaks, that can also speed up my implementation.
Thanks,
Auto Vimal.
